---

title: My Blog
author: Jason Naramore
email: wjnaramore@gmail.com
# description: > # this means "folded" block
  # A simple blog powered by Jekyll and GitHub Pages.

description:  
theme: minima

# Optional: social links (minima supports these)

# Build settings

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-archives
  - jekyll-paginate
  - jekyll-include-cache
  - jekyll-optional-front-matter
---

